apiVersion: ui.platform-mesh.io/v1alpha1
kind: ContentConfiguration
metadata:
  labels:
    ui.platform-mesh.io/entity: core_platform-mesh_io_account
    ui.platform-mesh.io/content-for: kube-bind.io
  name: kube-bind-ui
spec:
  inlineConfiguration:
    content: |-
      {
          "name": "kube-bind-ui",
          "luigiConfigFragment": {
              "data": {
                  "nodes": [
                      {
                          "category": {
                              "label": "Kube Bind",
                              "icon": "chain-link",
                              "collapsible": false
                          },
                          "pathSegment": "binding-requests",
                          "label": "Binding Requests",
                          "hideFromNav": false,
                          "icon": "document",
                          "url": "http://localhost:4300/index.html#/requests",
                          "entityType": "main.core_platform-mesh_io_account",
                          "order": 800,
                          "loadingIndicator": {
                              "enabled": true
                          },
                          "context": {
                              "accountId": ":core_platform-mesh_io_accountId"
                          }
                      },
                      {
                          "category": {
                              "label": "Kube Bind",
                              "icon": "chain-link",
                              "collapsible": false
                          },
                          "pathSegment": "cluster-bindings",
                          "label": "Cluster Bindings",
                          "hideFromNav": false,
                          "icon": "chain-link",
                          "url": "http://localhost:4300/index.html#/bindings",
                          "entityType": "main.core_platform-mesh_io_account",
                          "order": 801,
                          "loadingIndicator": {
                              "enabled": true
                          },
                          "context": {
                              "accountId": ":core_platform-mesh_io_accountId"
                          }
                      },
                      {
                          "category": {
                              "label": "Kube Bind",
                              "icon": "chain-link",
                              "collapsible": false
                          },
                          "pathSegment": "service-mappings",
                          "label": "Service Mappings",
                          "hideFromNav": false,
                          "icon": "share-2",
                          "url": "http://localhost:4300/index.html#/service-mappings",
                          "entityType": "main.core_platform-mesh_io_account",
                          "order": 802,
                          "loadingIndicator": {
                              "enabled": true
                          },
                          "context": {
                              "accountId": ":core_platform-mesh_io_accountId"
                          }
                      }
                  ]
              }
          }
      }
    contentType: json
